version: '3'
services:
  news_db:
    container_name: news_db
    image: postgres:latest
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:       ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
